export const mainActionsTypes = {
  UPDATE_CURENT_LOCATION: 'UPDATE_CURENT_LOCATION',
  INITIALIZE_TIME: 'INITIALIZE_TIME',
  ADD_NEW_WEATHER_ITEM: 'ADD_NEW_WEATHER_ITEM'
};

export const utilsActionsTypes = {
  SHOW_MAP: 'SHOW_MAP',
  HIDE_MAP: 'HIDE_MAP'
};
