export default {
  UPDATE_CURENT_LOCATION: 'UPDATE_CURENT_LOCATION',
  INITIALIZE_TIME: 'INITIALIZE_TIME',
  ADD_NEW_WEATHER_ITEM: 'ADD_NEW_WEATHER_ITEM'
  // UPDATE_MAIN_WEATHER_DATA: 'UPDATE_MAIN_WEATHER_DATA',
  // TOGGLE_LOADER: 'TOGGLE_LOADER',
  // ADD_LOCATION_TO_MULTI_ARRAY: 'ADD_LOCATION_TO_MULTI_ARRAY',
  // REMOVE_LOCATION_FROM_MULTI_ARRAY: 'REMOVE_LOCATION_FROM_MULTI_ARRAY',
  // SHOW_MAP: 'SHOW_MAP',
  // HIDE_MAP: 'HIDE_MAP'
};
