export default {
  UPDATE_CURENT_LOCATION: 'UPDATE_CURENT_LOCATION',
  UPDATE_MAIN_WEATHER_DATA: 'UPDATE_MAIN_WEATHER_DATA',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  ADD_LOCATION_TO_MULTI_ARRAY: 'ADD_LOCATION_TO_MULTI_ARRAY',
  REMOVE_LOCATION_FROM_MULTI_ARRAY: 'REMOVE_LOCATION_FROM_MULTI_ARRAY'
};
